# Generated by Django 6.0.4 on 2026-06-14 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='status',
            field=models.CharField(choices=[('active', '有效'), ('expiring', '临期'), ('urgent', '紧急'), ('expired', '已过期'), ('archived', '已归档')], default='active', max_length=32, verbose_name='状态'),
        ),
    ]
